### ISSUE TITLE
`get-` and `resolve-` commands don't work yet?

### ISSUE THREAD

**Issue by abegong** [jbn/psychonaut#2]
Cool project and kudos for jumping on it so fast! I ignored your "bucket of slop" warning and tried out `psychonaut` anyway.

`poast` worked liked a charm.

Nothing else did. Command line output is below.

I'm guessing that these don't work b/c they just aren't built yet. But it's also possible that it's just user error.

In that case, you might be able to score some quick wins (e.g. by providing a few examples in docstrings).

```
> psychonaut resolve-handle abegong            
Traceback (most recent call last):
  File "/usr/local/bin/psychonaut", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/psychonaut/cli/util.py", line 9, in wrapper
    return asyncio.run(func(*args, **kwargs))
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/psychonaut/cli/useful_queries.py", line 34, in resolve_handle
    resp = await resolve_handle_f(sess, req)
  File "/usr/local/lib/python3.10/site-packages/psychonaut/api/lexicons/com/atproto/identity/resolve_handle.py", line 27, in resolve_handle
    resp = await sess.query(req)
  File "/usr/local/lib/python3.10/site-packages/psychonaut/api/session.py", line 43, in query
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://bsky.social/xrpc/com.atproto.identity.resolveHandle?handle=abegong')

```

```
> psychonaut resolve-handle abegong@bsky.social
Traceback (most recent call last):
  File "/usr/local/bin/psychonaut", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/psychonaut/cli/util.py", line 9, in wrapper
    return asyncio.run(func(*args, **kwargs))
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/psychonaut/cli/useful_queries.py", line 34, in resolve_handle
    resp = await resolve_handle_f(sess, req)
  File "/usr/local/lib/python3.10/site-packages/psychonaut/api/lexicons/com/atproto/identity/resolve_handle.py", line 27, in resolve_handle
    resp = await sess.query(req)
  File "/usr/local/lib/python3.10/site-packages/psychonaut/api/session.py", line 43, in query
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://bsky.social/xrpc/com.atproto.identity.resolveHandle?handle=abegong@bsky.social')
```

**Comment by jbn** [comment]
Heh, in the end, it _was_ user error, but user error that i replicated because it's still not obvious to me.

bsky uses `@name.domain` not `name@domain`

```
psychonaut resolve-handle @abegong.bsky.social
{"did": "did:plc:expoyhjkhbwocyjxb44oxijp"}
```

Your existing version should work but if you upgrade it it at least gives you a warning message in that _still_ slop of a stacktrace.

Thanks for submitting though. Cowpaths and all -- this clearly needed something that was clearer
